### ISSUE TITLE
`b2 0.7.1` - "Error: py-terraform-provider217643351: Failed to stat /proc/self/exe: Bad file descriptor" on Dockerized linux running on M1

### ISSUE THREAD

**Issue by ocyedwin** [Backblaze/terraform-provider-b2#29]
Encountered the following error just trying to setup a simple key.

```
Terraform will perform the following actions:

  # b2_application_key.b2_truenas_key will be created
  + resource "b2_application_key" "b2_truenas_key" {
      + application_key    = (sensitive value)
      + application_key_id = (known after apply)
      + capabilities       = [
          + "readFiles",
        ]
      + id                 = (known after apply)
      + key_name           = "b2-truenas-key"
      + options            = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

b2_application_key.b2_truenas_key: Creating...
╷
│ Error: py-terraform-provider217643351: Failed to stat /proc/self/exe: Bad file descriptor
│ 
│ 
│   with b2_application_key.b2_truenas_key,
│   on backblaze.tf line 4, in resource "b2_application_key" "b2_truenas_key":
│    4: resource "b2_application_key" "b2_truenas_key" {
```

**Comment by ppolewicz** [comment]
Hey, what environment did you run it on?.

**Comment by ocyedwin** [comment]
Hey @ppolewicz , ran it on the following setup:
- M1 MacBook Pro
  - Docker Desktop 4.3
    - Linux/AMD64 Ubuntu 20.04

**Comment by ppolewicz** [comment]
Can you please try it on a non-M1-based platform?

**Comment by ppolewicz** [comment]
I think maybe amd64 linux running on M1 is not a supported configuration - not just by b2 terraform provider but by other things as well. You may either reduce the level of encapsulation by removing docker from the mix or add levels by using a ("full") VM

**Comment by ocyedwin** [comment]
@ppolewicz I feel its b2 provider implementation specifics rather than Docker/M1 because I'm using `digitalocean/digitalocean`, `dnsimple/dnsimple`, `hashicorp/google`, `Heroku/heroku`, `cloudflare/cloudflare` on same setup with no issue ...

**Comment by ppolewicz** [comment]
yes, b2 provider implementation is a little bit specific and may be fragile in rare environments

**Comment by mszumocki-reef** [comment]
This seems to be related to an obscure interaction between Pyinstaller and qemu-static used by Docker on M1, and according to Pyinstaller changelog it has been fixed in Pyinstaler 4.4. Hopefully upgrading Pyinstaller will solve this, however I cannot test it myself as I don't have an Apple with M1 silicon.
Please test with 0.8.0 release once it's ready.

**Comment by Fizzadar** [comment]
Running into this today; problem still happens for me under v0.8.1.

**Comment by ppolewicz** [comment]
@Fizzadar can you please confirm what environment you are trying to run it on?

**Comment by Fizzadar** [comment]
@ppolewicz this is inside an x86 Docker container on an M1 mac using docker desktop.
